#!/usr/bin/env python3
"""Materialize the case-variant sweep shim headers on case-sensitive filesystems.

The original Westwood sources `#include` some headers under two spellings that
differ only in case (e.g. both `"stdafx.h"` and `"stdAfx.h"`, `"Mss.H"` and
`"mss.h"`). On a case-sensitive filesystem (Linux) both spellings must resolve,
so historically BOTH files were committed. But two paths differing only in case
cannot coexist in a Windows/macOS working tree — git checks out one and drops the
other, breaking the build (and emitting a scary "paths have collided" warning).

Fix: commit ONE canonical file per pair; regenerate the alternate spelling here as
a tiny redirect stub, only when the filesystem is case-sensitive. On a
case-insensitive filesystem the single committed file already answers both
spellings, so this is a no-op there. The stub redirects to the canonical (which
carries an include guard) rather than duplicating its body, so a translation unit
that includes both spellings still sees the content exactly once.

build.py calls ensure_case_shims() before compiling; it is also runnable directly
(e.g. from a post-checkout hook).
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SWEEP = ROOT / "reference" / "shims" / "sweep"

# (canonical committed file, alternate-case sibling, redirect line for the stub).
# The redirect line reproduces how the original sources reach the canonical.
_PAIRS = [
    ("Mss.H",              "mss.h",              '#include "Mss.H"'),
    ("wsys/File.h",        "wsys/file.h",        '#include <wsys/File.h>'),
    ("stdafx.h",           "stdAfx.h",           '#include "stdafx.h"'),
    ("worldbuilder.h",     "WorldBuilder.h",     '#include "worldbuilder.h"'),
    ("wpaudio/source.h",   "wpaudio/Source.h",   '#include "source.h"'),
    ("d3dx8math.h",        "D3DX8Math.h",        '#include "d3dx8math.h"'),
]

_MARKER = "// Generated by tools/gen_case_shims.py — do not edit or commit."


def ensure_case_shims(sweep_dir=SWEEP):
    """Create the alternate-case redirect stubs next to their canonical headers.

    Returns the list of paths written (empty on a case-insensitive filesystem or
    when everything is already current). Raises if a canonical header is missing —
    a missing canonical is a real breakage, never something to paper over.
    """
    written = []
    for canon_rel, alt_rel, line in _PAIRS:
        canon = sweep_dir / canon_rel
        alt = sweep_dir / alt_rel
        if not canon.exists():
            raise SystemExit(
                f"gen_case_shims: canonical header missing: {canon}\n"
                f"  the committed shim for this pair is gone; restore it from git."
            )
        # On a case-insensitive filesystem `alt` resolves to `canon` itself — one
        # file already serves both spellings, so there is nothing to generate.
        if alt.exists() and os.path.samefile(canon, alt):
            continue
        want = f"{_MARKER}\n{line}\n"
        if alt.exists() and alt.read_text(encoding="utf-8", errors="replace") == want:
            continue
        alt.parent.mkdir(parents=True, exist_ok=True)
        alt.write_text(want, encoding="utf-8")
        written.append(alt)
    return written


if __name__ == "__main__":
    made = ensure_case_shims()
    if made:
        print(f"gen_case_shims: wrote {len(made)} case-variant shim(s):")
        for p in made:
            print(f"  {p.relative_to(ROOT)}")
    else:
        print("gen_case_shims: nothing to do (case-insensitive FS or already current)")
    sys.exit(0)
